# Generated by Django 4.1.1 on 2022-11-30 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=120, null=True)),
                ('dateTime', models.DateTimeField(null=True)),
                ('maxParticipants', models.IntegerField(null=True)),
                ('participants', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraineeData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveIntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('bio', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainerPicker.groupclass')),
                ('traineeID', models.ManyToManyField(to='trainerPicker.traineedata')),
            ],
        ),
        migrations.AddField(
            model_name='groupclass',
            name='trainerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainerPicker.trainerdata'),
        ),
    ]
