# Generated by Django 4.1.1 on 2022-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerPicker', '0002_alter_trainingsession_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='participants',
            field=models.JSONField(null=True),
        ),
    ]
