# Generated by Django 4.1.1 on 2022-11-27 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainerPicker', '0003_trainingsession_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingSession',
            new_name='GroupClass',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainerPicker.groupclass')),
            ],
        ),
    ]
